borisfacts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('yourstories.urls')),
    url(r'^admin/', admin.site.urls),
]

yourstories/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'yourstories'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^stories/$', views.index, name='index'),
    url(r'^stories/post/$', views.post, name='post'),
    url(r'^stories/post/handler/$', views.post_handler, name='post_handler'),
    url(r'^stories/(?P<id>[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12})/$', views.story, name='story'),
    url(r'^stories/(?P<id>[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12})/verify/(?P<code>[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12})/$', views.verify, name='verify')
]

yourstories/models.py
import uuid
from datetime import datetime
from django.db import models

class Story(models.Model):
    class Meta:
        verbose_name_plural = 'stories'

    # Primary Key
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Public fields
    title = models.CharField(max_length=100)
    content = models.TextField()
    submitted_at = models.DateTimeField(default=datetime.now)
    author = models.CharField(max_length=100, null=True)

    # Admin fields
    author_email = models.EmailField()
    author_email_verified = models.BooleanField(default=False, editable=False)
    email_verification_code = models.UUIDField(default=uuid.uuid4, null=True, editable=False)
    published = models.BooleanField(default=False)

    # Additional methods
    def __str__(self):
        return self.title

yourstories/views.py
from uuid import UUID
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import mail_admins, send_mail
from django.template.loader import render_to_string

from .models import Story

def home(request):
    return render(request, 'home.html', dict(num_stories=Story.objects.filter(published=True).count(), stories=Story.objects.filter(published=True).order_by('-submitted_at')[0:5]))

def index(request):
    return render(request, 'index.html', dict(stories=Story.objects.filter(published=True).order_by('-submitted_at')))

def post(request):
    return render(request, 'submit.html', dict(previous={}))

def post_handler(request):
    def error(msg):
        return render(request, 'submit.html', dict(error_message=msg, previous=request.POST))
    story_dict = {}
    try:
        story_dict['title'] = request.POST['title']
    except KeyError as e:
        return error('Please add a title')
    try:
        story_dict['content'] = request.POST['content']
    except KeyError as e:
        return error('Please add some content')
    try:
        story_dict['author'] = request.POST['author']
    except KeyError as e:
        story_dict['author'] = None
    try:
        story_dict['author_email'] = request.POST['author_email']
    except KeyError as e:
        return error('Please provide an email address. We will need it to verify your story.')

    story = Story(**story_dict)
    story.save()
    mail_admins(
        subject='New story submitted: {} by {}'.format(story.title, story.author or 'Anonymous'),
        message='A new story was submitted, please view it on the admin portal. Id: {}'.format(story.id)
    )
    send_mail(
        subject='Please confirm your email address for borisfucked.me story submission',
        message=render_to_string('email.html', dict(story=story)),
        from_email='noreply@borisfucked.me',
        recipient_list=[story.author_email]
    )
    return HttpResponseRedirect(reverse('yourstories:story', args=(story.id,)))

def story(request, id):
    return render(request, 'story.html', dict(story=get_object_or_404(Story, pk=id)))

def verify(request, id, code):
    story = get_object_or_404(Story, pk=id)
    if UUID(code) == story.email_verification_code:
        story.author_email_verified = True
        story.save()
        return HttpResponseRedirect(reverse('yourstories:story', args=(story.id,)))
    else:
        return render(request, 'error.html', dict(message='Sorry, confirmation failed. Story could be already confirmed.'))

yourstories/templates/email.html
Hi {{story.author|default:'Anonymous'}},

Your story, {{story.title}}, is almost ready to be published on
borisfucked.me.

Before we publish your story, we would like you to confirm your email address
for us. To do so, simply visit the link below:

http://borisfucked.me{% url 'yourstories:verify' story.id story.email_verification_code %}

Best regards,
borisfucked.me admin

yourstories/templates/error.html
{% extends 'layouts/master.html' %}

{% block title %}Error | Boris Fucked Me{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col span-12-t">
      <p class="error">
        {{message}}
      </p>
    </div>
  </div>
</div>
{% endblock %}

yourstories/templates/home.html
{% extends 'layouts/master.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col span-12-t">
      <h2>Your Stories</h2>
      <p>
        We would like to hear from you about how Brexit is affecting you. We have a total of {{ num_stories }} stor{% if num_stories == 1 %}y{% else %}ies{% endif %} already.
      </p>
      {% if num_stories > 0 %}
        <p>
          The most recent stories:
        </p>
        <ul>
          {% for story in stories %}
            <li><a href="{% url 'yourstories:story' story.id %}">{{ story.title }}</a> &mdash; {{ story.submitted_at }}</a></li>
          {% endfor %}
        </ul>
      {% endif %}
      <p>
        <a href="{% url 'yourstories:index' %}">See more</a> or <a href="{% url 'yourstories:post' %}">submit your own</a>.
      </p>
      <h2>The Obvious</h2>
      <ul>
        <li>Even after <a href="http://www.itv.com/news/2016-05-11/uk-does-get-back-some-of-350m-it-sends-to-eu-boris-johnson-admits/">admitting that this is not the case</a>, Boris continued to use the £350m per week figure to mislead the public into voting Leave.</li>
        <li>Moments after the referendum results were announced, <a href="http://www.telegraph.co.uk/business/2016/06/27/george-osborne-to-speak-in-attempt-to-calm-markets-following-bre/">the Pound and the markets dropped harder than Skrillex's career</a> and we're still not done.</li>
      </ul>
      <h2>The Less Obvious</h2>
      <ul>
        <li>The referendum may never have been about racism or bigotry, but it certainly emboldened racists and bigots. See <a href="https://twitter.com/PostRefRacism">@PostRefRacism on Twitter</a>.</li>
        <li><a href="http://www.independent.co.uk/news/uk/politics/brexit-eu-referendum-campaigners-there-is-no-plan-next-pm-tory-leadership-contest-a7104711.html">There is no plan,</a> according to one Brexit campaigner.</li>
        <li>The referendum triggered <a href="http://www.theguardian.com/politics/2016/jun/26/labour-shadow-cabinet-resignations-jeremy-corbyn-who-has-gone">a massive shadow cabinet reshuffle</a>, with many senior officials leaving.</li>
        <li>The UK may stay in the single market... <a href="http://www.theguardian.com/politics/2016/jun/27/brussels-rejects-boris-johnson-pipe-dream-over-single-market-access">provided it accepts the EU rules without having a say over them</a>.</li>
      </ul>
    </div>
  </div>
</div>

<div class="container video">
  <div class="row">
    <div class="col span-12-t">
      <h2>And The Piggy</h2>
    </div>
    <div class="col span-12-t ytembed">
      <iframe src="https://www.youtube.com/embed/rETo8MJ8NuA" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</div>
{% endblock %}

yourstories/templates/index.html
{% extends 'layouts/master.html' %}

{% block title %}Your Stories | Boris Fucked Me{% endblock %}
{% block twtitle %}Your Stories | Boris Fucked Me{% endblock %}
{% block fbtitle %}Your Stories | Boris Fucked Me{% endblock %}
{% block link %}{% url 'yourstories:index' %}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col span-12-t">
        {% if stories %}
          {% for story in stories %}
            {% include 'partials/_story.html' %}
          {% endfor %}
        {% else %}
          <p>No stories yet. <a href="{% url 'yourstories:post' %}">Submit one?</a></p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

yourstories/templates/layouts/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Boris Fucked Me{% endblock %}</title>
  <meta name="description" content="Dispatches from a post-referendum Britain. Tracking the damage Boris & Co have wrought.">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css">
  <link rel="stylesheet" href="https://cdn.rawgit.com/jkymarsh/tiny-responsive-grid/master/trg.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/typeplate-starter-kit/3.0.1/css/typeplate.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}" charset="utf-8">

  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="{% block twtitle %}Boris Fucked Me{% endblock %}">
  <meta name="twitter:description" content="Dispatches from a post-referendum Britain. Tracking the damage Boris & Co have wrought.">
  <meta name="twitter:creator" content="@Minkovsky">
  <meta name="twitter:image" content="http://www.borisfucked.me{% static 'socialcover.jpg' %}">

  <!-- Open Graph data -->
  <meta property="og:title" content="{% block fbtitle %}Boris Fucked Me{% endblock %}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="http://www.borisfucked.me{% block link %}/{% endblock %}" />
  <meta property="og:description" content="Dispatches from a post-referendum Britain. Tracking the damage Boris & Co have wrought." />
  <meta property="og:site_name" content="borisfucked.me" />
  <meta property="og:image" content="http://www.borisfucked.me{% static 'socialcover.jpg' %}">

</head>
<body>
  <div class="container banner">
    <h1><a href="{% url 'yourstories:home' %}">Boris Fucked Me</a></h1>
    <p>A site dedicated to tracking the damage Boris has done.</p>
  </div>
  {% block content %}{% endblock %}
  <div class="container">
    <div class="row">
      <div class="col span-12-t">
        <hr>
        <h4>About This</h4>
        <p>
          We want to create a comprehensive archive of how the referendum result and the potential Brexit impacts people, and how this result came into being.
        </p>
        <p>We need more. We are looking for stories about how Boris Johonson or the Brexit in general affected you negatively, as well as ways in which he may have misled the public into
          voting to leave the European Union. Over the coming days and weeks, we will be working on a way for you to submit your own personal post-Brexit story.</p>
        <p><a href="https://github.com/FLamparski/borisfacts">Contribute to the list on GitHub</a></p>
        <p>
          Site made by <a href="https://twitter.com/Minkovsky">@Minkovsky</a>. Video made by <a href="https://twitter.com/TomSFHaines">Tom</a>. Social media image made by <a href="https://twitter.com/olderThanevil">@olderThanevil</a>.
        </p>
      </div>
    </div>
  </div>
</body>
</html>

yourstories/templates/partials/_story.html
<article class="story" id="story-{{ story.id }}">
  <header>
    <h3><a href="{% url 'yourstories:story' story.id %}">{{ story.title }}</a></h3>
    <p class="byline">Submitted by {{ story.author|default:'Anonymous' }} on {{ story.submitted_at }}</p>
  </header>
  <div class="content">
    {{ story.content|linebreaks }}
  </div>
</article>

yourstories/templates/story.html
{% extends 'layouts/master.html' %}

{% block title %}{{ story.title }} | Boris Fucked Me{% endblock %}
{% block twtitle %}{{ story.title }}{% endblock %}
{% block fbtitle %}{{ story.title }}{% endblock %}
{% block link %}{% url 'yourstories:story' story.id %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col span-12-t">
      {% if not story.published %}
        <p>
          This story is not published and will not appear on the list. Please wait for a moderator to approve it.
        </p>
      {% endif %}
      {% include 'partials/_story.html' %}
    </div>
  </div>
</div>
{% endblock %}

yourstories/templates/submit.html
{% extends 'layouts/master.html' %}

{% block title %}Submit Story | Boris Fucked Me{% endblock %}
{% block twtitle %}Submit Your Boris Fucked Me Story{% endblock %}
{% block fbtitle %}Submit Your Boris Fucked Me Story{% endblock %}
{% block link %}{% url 'yourstories:post' %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col span-12-t">
      <h2>Submit Your Story</h2>
      {% if error_message %}
        <p class="error">
          {{ error_message }}
        </p>
      {% endif %}
      <form id="submit-story" action="{% url 'yourstories:post_handler' %}" method="post">
        {% csrf_token %}
        <fieldset>
          <label for="title">Title</label>
          <input type="text" name="title" id="title" required autofocus value="{{ previous.title }}">
        </fieldset>
        <div class="row gutters-d">
          <div class="col span-12-t span-6-d">
            <fieldset>
              <label for="author">Display Name</label>
              <input type="text" name="author" id="author" value="{{ previous.author }}">
              <small class="form-help">The value is displayed. Leave blank if you wish.</small>
            </fieldset>
          </div>
          <div class="col span-12-t span-6-d">
            <fieldset>
              <label for="author_email">Your Email Address</label>
              <input type="email" name="author_email" id="author_email" required value="{{ previous.author_email }}">
              <small class="form-help">Your email address will not be displayed, and is used for email verification. We will not pass on your email address to third parties.</small>
            </fieldset>
          </div>
        </div>
        <fieldset>
          <label for="content">Content</label>
          <textarea name="content" rows="8" cols="40" required id="content">{{ previous.content }}</textarea>
        </fieldset>
        <button type="submit">Submit Story</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}